### ISSUE TITLE
Some Problems with installing Sparse Transformer

### ISSUE THREAD

**Issue by hellohaozheng** [dvlab-research/SphereFormer#25]
Hello! Thanks to your excellent work. I'd like to know How Much memory need to be used when training.

My work station is in Ubuntu22.04 with CUDA11.7

I found such a problem below:
![image](https://user-images.githubusercontent.com/74909571/236362215-b620c14c-1f0d-4d5c-8d16-ca83dd83fd4a.png)

**Comment by X-Lai** [comment]
Can you figure out which line causes the segment error?

**Comment by hellohaozheng** [comment]
When I install sparse transformer, there is such a problem:
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/74909571/236381900-822e5e1e-2560-4be5-be9d-67dca284c50b.png">

I couldn't find these 3 files in folders as well. Therefore, I noted the 3 rows.
<img width="551" alt="image" src="https://user-images.githubusercontent.com/74909571/236382001-320a8deb-7911-4710-bd14-835e7ce9f458.png">

But I cannot import sptr correctly.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/74909571/236382048-a192c468-1cb9-421f-befb-2fb8ff5f3eb8.png">

It seems a problem about sptr installation.

**Comment by hellohaozheng** [comment]
> Can you figure out which line causes the segment error?
I found the problem occured when 
`from util.data_util import collate_fn_limit, collation_fn_voxelmean, collation_fn_voxelmean_tta`

**Comment by X-Lai** [comment]
Please uncomment these three `.cu` files. And compile again.

**Comment by hellohaozheng** [comment]
> Please uncomment these three `.cu` files. And compile again.

When I uncommented the rows, there were loss of files.
`/home/hhz/.conda/envs/spformer/compiler_compat/ld: cannot find /home/hhz/code/segmentation/SphereFormer/third_party/SparseTransformer/build/temp.linux-x86_64-cpython-37/src/sptr/attention/attention_cuda_kernel.o: 没有那个文件或目录
/home/hhz/.conda/envs/spformer/compiler_compat/ld: cannot find /home/hhz/code/segmentation/SphereFormer/third_party/SparseTransformer/build/temp.linux-x86_64-cpython-37/src/sptr/precompute/precompute_cuda_kernel.o: 没有那个文件或目录
/home/hhz/.conda/envs/spformer/compiler_compat/ld: cannot find /home/hhz/code/segmentation/SphereFormer/third_party/SparseTransformer/build/temp.linux-x86_64-cpython-37/src/sptr/rpe/relative_pos_encoding_cuda_kernel.o: 没有那个文件或目录
collect2: error: ld returned 1 exit status
error: command '/usr/bin/g++' failed with exit code 1`

**Comment by X-Lai** [comment]
Have you installed `nvcc`? Can you input `nvcc -V` in the terminal to see whether it is installed correctly?

**Comment by hellohaozheng** [comment]
> Have you installed `nvcc`? Can you input `nvcc -V` in the terminal to see whether it is installed correctly?

Yes, I have installed nvcc correctly.

`$ nvcc -V`
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0`

**Comment by X-Lai** [comment]
It is a little weird. Do you strictly follow the command in README, like you need to first enter the `third_party/SparseTransformer`, and then execute the `python setup.py install` ?

**Comment by brahami14** [comment]
hello, thank you for this work, 
i have a probleme with installation of Sparse Transformer, 

i try to install it by using CUDA 11.6, so i got this error i don't understand why 
![image](https://github.com/dvlab-research/SphereFormer/assets/103207573/1582df39-5e83-4050-9234-3c7d3df4182f)

**Comment by brahami14** [comment]
do you have an idea how to fixe it whene we use venv

**Comment by X-Lai** [comment]
Hi, Can you try to follow the solution here: https://github.com/dvlab-research/SparseTransformer/issues/2

**Comment by brahami14** [comment]
Thank you so much for your response, now i  have this error,


 virtual_env/venv_with_python3.8/lib/python3.8/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 11.6
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
building 'sptr_cuda' extension
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    setup(
  File "virtual_env/venv_with_python3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/shared/home/sc43822/virtual_env/venv_with_python3.8/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/shared/home/sc43822/virtual_env/venv_with_python3.8/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/shared/home/sc43822/virtual_env/venv_with_python3.8/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/shared/home/sc43822/virtual_env/venv_with_python3.8/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/shared/home/sc43822/virtual_env/venv_with_python3.8/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python3.8/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/shared/home/sc43822/virtual_env/venv_with_python3.8/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/shared/home/sc43822/virtual_env/venv_with_python3.8/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/shared/home/sc43822/virtual_env/venv_with_python3.8/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
    build_ext.build_extensions(self)
  File "/shared/home/sc43822/virtual_env/venv_with_python3.8/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/shared/home/sc43822/virtual_env/venv_with_python3.8/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/shared/home/sc43822/virtual_env/venv_with_python3.8/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 581, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/shared/home/sc43822/virtual_env/venv_with_python3.8/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 480, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/shared/home/sc43822/virtual_env/venv_with_python3.8/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1694, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

**Comment by brahami14** [comment]
thank you so much it works @X-Lai

**Comment by brahami14** [comment]
now i have this issue, do you have any idea why ?
![image](https://github.com/dvlab-research/SphereFormer/assets/103207573/1ee5e295-18cc-4738-ab95-e74e4e80ce9f)

**Comment by X-Lai** [comment]
Have you modified the original code? I think maybe the shape of `pos` or `batch` is incorrect. Can you confirm that?

**Comment by brahami14** [comment]
hello, i modified just the number of GPUs, 

batch:  torch.Size([683865])
pos: torch.Size([683865, 3])
size: tensor([0.3000, 0.3000, 0.3000], device='cuda:0')

**Comment by brahami14** [comment]
it's ok,  the problem is solved, the issue   was about the version of torch-geometric, i used 0.5 instead if 1.7.
Thank you so much for your help
