### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by rsleishaui** [dvlab-research/SphereFormer#27]
执行验证的时候出现的错误，您知道这是什么原因吗
Traceback (most recent call last):
  File "train.py", line 902, in <module>
    main()
  File "train.py", line 90, in main
    mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args.ngpus_per_node, args))
  File "/root/anaconda3/envs/ST/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/anaconda3/envs/ST/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/root/anaconda3/envs/ST/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 144, in join
    exit_code=exitcode
torch.multiprocessing.spawn.ProcessExitedException: process 2 terminated with exit code 1

**Comment by X-Lai** [comment]
可以给更具体的报错吗？

**Comment by Isaac-xie** [comment]
我遇到了同样的问题

```
[05/23 14:49:09 main-logger]: #Model parameters: 32311616
[05/23 14:49:09 main-logger]: class_weight: None
[05/23 14:49:09 main-logger]: loss_name: ce_loss
[05/23 14:49:09 main-logger]: => loading weight '/media/data2/xzz/code/SphereFormer/SphereFormer/ckpt/model_nuscenes.pth'
[05/23 14:49:09 main-logger]: => loaded weight '/media/data2/xzz/code/SphereFormer/SphereFormer/ckpt/model_nuscenes.pth'
[05/23 14:49:15 main-logger]: train_data samples: '28130'
[05/23 14:49:17 main-logger]: val_data samples: '6019'
[05/23 14:49:17 main-logger]: scheduler: Poly. scheduler_update: step
[05/23 14:49:17 main-logger]: >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
[05/23 14:49:35 main-logger]: Test: [10/753] Data 0.000 (1.278) Batch 0.466 (1.878) Loss 2.0142 (1.9635) Accuracy 0.8659.
[05/23 14:49:40 main-logger]: Test: [20/753] Data 0.000 (0.639) Batch 0.492 (1.180) Loss 1.9756 (1.9653) Accuracy 0.9097.
[05/23 14:49:45 main-logger]: Test: [30/753] Data 0.000 (0.426) Batch 0.465 (0.939) Loss 1.9409 (1.9645) Accuracy 0.9472.
[05/23 14:49:49 main-logger]: Test: [40/753] Data 0.000 (0.320) Batch 0.408 (0.816) Loss 2.0005 (1.9587) Accuracy 0.8982.
[05/23 14:49:54 main-logger]: Test: [50/753] Data 0.000 (0.256) Batch 0.483 (0.749) Loss 1.9047 (1.9555) Accuracy 0.9782.
[05/23 14:49:58 main-logger]: Test: [60/753] Data 0.000 (0.213) Batch 0.471 (0.700) Loss 1.9212 (1.9528) Accuracy 0.9627.
[05/23 14:50:03 main-logger]: Test: [70/753] Data 0.000 (0.183) Batch 0.411 (0.660) Loss 1.9136 (1.9470) Accuracy 0.9696.
[05/23 14:50:07 main-logger]: Test: [80/753] Data 0.000 (0.160) Batch 0.399 (0.629) Loss 1.8997 (1.9416) Accuracy 0.9801.
[05/23 14:50:11 main-logger]: Test: [90/753] Data 0.000 (0.142) Batch 0.367 (0.604) Loss 1.8995 (1.9428) Accuracy 0.9828.
[05/23 14:50:15 main-logger]: Test: [100/753] Data 0.000 (0.128) Batch 0.502 (0.589) Loss 1.9082 (1.9392) Accuracy 0.9782.
[05/23 14:50:20 main-logger]: Test: [110/753] Data 0.000 (0.116) Batch 0.431 (0.575) Loss 1.9028 (1.9375) Accuracy 0.9795.
[05/23 14:50:24 main-logger]: Test: [120/753] Data 0.000 (0.107) Batch 0.411 (0.561) Loss 1.8939 (1.9344) Accuracy 0.9823.
[05/23 14:50:28 main-logger]: Test: [130/753] Data 0.000 (0.099) Batch 0.390 (0.550) Loss 1.9277 (1.9326) Accuracy 0.9563.
[05/23 14:50:32 main-logger]: Test: [140/753] Data 0.000 (0.092) Batch 0.384 (0.540) Loss 1.9399 (1.9312) Accuracy 0.9481.
[05/23 14:50:36 main-logger]: Test: [150/753] Data 0.000 (0.085) Batch 0.433 (0.531) Loss 1.8953 (1.9315) Accuracy 0.9882.
[05/23 14:50:41 main-logger]: Test: [160/753] Data 0.000 (0.080) Batch 0.410 (0.527) Loss 1.9251 (1.9301) Accuracy 0.9567.
[05/23 14:50:45 main-logger]: Test: [170/753] Data 0.000 (0.075) Batch 0.488 (0.523) Loss 1.9189 (1.9307) Accuracy 0.9692.
[05/23 14:50:50 main-logger]: Test: [180/753] Data 0.000 (0.071) Batch 0.465 (0.522) Loss 1.9156 (1.9308) Accuracy 0.9735.
[05/23 14:50:55 main-logger]: Test: [190/753] Data 0.000 (0.068) Batch 0.500 (0.520) Loss 1.9493 (1.9309) Accuracy 0.9392.
[05/23 14:51:00 main-logger]: Test: [200/753] Data 0.000 (0.064) Batch 0.505 (0.518) Loss 1.9676 (1.9316) Accuracy 0.9225.
[05/23 14:51:05 main-logger]: Test: [210/753] Data 0.000 (0.061) Batch 0.538 (0.516) Loss 1.9230 (1.9316) Accuracy 0.9622.
[05/23 14:51:09 main-logger]: Test: [220/753] Data 0.000 (0.058) Batch 0.445 (0.513) Loss 1.9129 (1.9317) Accuracy 0.9725.
[05/23 14:51:14 main-logger]: Test: [230/753] Data 0.000 (0.056) Batch 0.431 (0.509) Loss 1.9175 (1.9312) Accuracy 0.9699.
[05/23 14:51:18 main-logger]: Test: [240/753] Data 0.000 (0.054) Batch 0.534 (0.508) Loss 1.9261 (1.9308) Accuracy 0.9602.
[05/23 14:51:23 main-logger]: Test: [250/753] Data 0.000 (0.051) Batch 0.446 (0.508) Loss 1.9225 (1.9300) Accuracy 0.9596.
[05/23 14:51:28 main-logger]: Test: [260/753] Data 0.000 (0.049) Batch 0.432 (0.506) Loss 1.9072 (1.9293) Accuracy 0.9759.
[05/23 14:51:32 main-logger]: Test: [270/753] Data 0.000 (0.048) Batch 0.408 (0.502) Loss 1.9833 (1.9311) Accuracy 0.8979.
[05/23 14:51:37 main-logger]: Test: [280/753] Data 0.000 (0.046) Batch 0.458 (0.500) Loss 1.9334 (1.9308) Accuracy 0.9535.
[05/23 14:51:41 main-logger]: Test: [290/753] Data 0.000 (0.044) Batch 0.384 (0.498) Loss 1.8972 (1.9304) Accuracy 0.9807.
[05/23 14:51:45 main-logger]: Test: [300/753] Data 0.000 (0.043) Batch 0.464 (0.495) Loss 1.8851 (1.9295) Accuracy 0.9929.
[05/23 14:51:49 main-logger]: Test: [310/753] Data 0.000 (0.041) Batch 0.428 (0.492) Loss 1.8885 (1.9284) Accuracy 0.9904.
[05/23 14:51:53 main-logger]: Test: [320/753] Data 0.000 (0.040) Batch 0.420 (0.490) Loss 1.9318 (1.9279) Accuracy 0.9533.
[05/23 14:51:58 main-logger]: Test: [330/753] Data 0.000 (0.039) Batch 0.461 (0.488) Loss 1.9127 (1.9275) Accuracy 0.9704.
[05/23 14:52:02 main-logger]: Test: [340/753] Data 0.000 (0.038) Batch 0.437 (0.486) Loss 1.8979 (1.9270) Accuracy 0.9845.
[05/23 14:52:06 main-logger]: Test: [350/753] Data 0.000 (0.037) Batch 0.380 (0.484) Loss 1.8960 (1.9265) Accuracy 0.9830.
[05/23 14:52:10 main-logger]: Test: [360/753] Data 0.000 (0.036) Batch 0.375 (0.481) Loss 1.9785 (1.9270) Accuracy 0.9076.
[05/23 14:52:14 main-logger]: Test: [370/753] Data 0.000 (0.035) Batch 0.400 (0.479) Loss 2.0152 (1.9272) Accuracy 0.8712.
[05/23 14:52:18 main-logger]: Test: [380/753] Data 0.000 (0.034) Batch 0.433 (0.477) Loss 1.9723 (1.9274) Accuracy 0.9122.
[05/23 14:52:22 main-logger]: Test: [390/753] Data 0.000 (0.033) Batch 0.411 (0.475) Loss 1.9080 (1.9280) Accuracy 0.9724.
[05/23 14:52:26 main-logger]: Test: [400/753] Data 0.000 (0.032) Batch 0.374 (0.474) Loss 1.9065 (1.9282) Accuracy 0.9792.
[05/23 14:52:30 main-logger]: Test: [410/753] Data 0.000 (0.031) Batch 0.425 (0.473) Loss 1.9359 (1.9280) Accuracy 0.9472.
[05/23 14:52:35 main-logger]: Test: [420/753] Data 0.000 (0.031) Batch 0.424 (0.472) Loss 1.9401 (1.9281) Accuracy 0.9419.
[05/23 14:52:39 main-logger]: Test: [430/753] Data 0.000 (0.030) Batch 0.418 (0.471) Loss 1.9546 (1.9286) Accuracy 0.9242.
[05/23 14:52:43 main-logger]: Test: [440/753] Data 0.000 (0.029) Batch 0.407 (0.470) Loss 1.8885 (1.9279) Accuracy 0.9907.
[05/23 14:52:47 main-logger]: Test: [450/753] Data 0.000 (0.029) Batch 0.437 (0.469) Loss 1.8943 (1.9272) Accuracy 0.9859.
[05/23 14:52:52 main-logger]: Test: [460/753] Data 0.000 (0.028) Batch 0.456 (0.468) Loss 1.9064 (1.9269) Accuracy 0.9756.
[05/23 14:52:57 main-logger]: Test: [470/753] Data 0.000 (0.027) Batch 0.478 (0.469) Loss 1.9255 (1.9271) Accuracy 0.9610.
[05/23 14:53:02 main-logger]: Test: [480/753] Data 0.000 (0.027) Batch 0.472 (0.469) Loss 1.9950 (1.9278) Accuracy 0.8855.
[05/23 14:53:07 main-logger]: Test: [490/753] Data 0.000 (0.026) Batch 0.522 (0.470) Loss 1.9416 (1.9282) Accuracy 0.9445.
[05/23 14:53:12 main-logger]: Test: [500/753] Data 0.000 (0.026) Batch 0.557 (0.471) Loss 1.9201 (1.9282) Accuracy 0.9650.
[05/23 14:53:16 main-logger]: Test: [510/753] Data 0.000 (0.025) Batch 0.435 (0.469) Loss 1.9162 (1.9281) Accuracy 0.9661.
[05/23 14:53:20 main-logger]: Test: [520/753] Data 0.000 (0.025) Batch 0.461 (0.469) Loss 1.9162 (1.9281) Accuracy 0.9693.
[05/23 14:53:24 main-logger]: Test: [530/753] Data 0.000 (0.024) Batch 0.396 (0.468) Loss 2.0044 (1.9288) Accuracy 0.7962.
[05/23 14:53:29 main-logger]: Test: [540/753] Data 0.000 (0.024) Batch 0.431 (0.467) Loss 1.9043 (1.9285) Accuracy 0.9761.
[05/23 14:53:33 main-logger]: Test: [550/753] Data 0.000 (0.023) Batch 0.418 (0.466) Loss 1.9493 (1.9285) Accuracy 0.9361.
[05/23 14:53:37 main-logger]: Test: [560/753] Data 0.000 (0.023) Batch 0.422 (0.465) Loss 1.9171 (1.9284) Accuracy 0.9591.
[05/23 14:53:42 main-logger]: Test: [570/753] Data 0.000 (0.023) Batch 0.533 (0.466) Loss 1.9479 (1.9289) Accuracy 0.9422.
[05/23 14:53:47 main-logger]: Test: [580/753] Data 0.000 (0.022) Batch 0.429 (0.467) Loss 1.9484 (1.9288) Accuracy 0.9362.
[05/23 14:53:52 main-logger]: Test: [590/753] Data 0.000 (0.022) Batch 0.449 (0.467) Loss 1.9327 (1.9292) Accuracy 0.9518.
[05/23 14:53:57 main-logger]: Test: [600/753] Data 0.000 (0.022) Batch 0.489 (0.467) Loss 1.9563 (1.9295) Accuracy 0.9271.
[05/23 14:54:02 main-logger]: Test: [610/753] Data 0.000 (0.021) Batch 0.442 (0.468) Loss 1.9279 (1.9296) Accuracy 0.9649.
[05/23 14:54:07 main-logger]: Test: [620/753] Data 0.000 (0.021) Batch 0.543 (0.468) Loss 1.9486 (1.9301) Accuracy 0.9400.
[05/23 14:54:12 main-logger]: Test: [630/753] Data 0.000 (0.021) Batch 0.489 (0.468) Loss 1.9342 (1.9302) Accuracy 0.9521.
[05/23 14:54:16 main-logger]: Test: [640/753] Data 0.000 (0.020) Batch 0.441 (0.468) Loss 1.9455 (1.9302) Accuracy 0.9406.
[05/23 14:54:21 main-logger]: Test: [650/753] Data 0.000 (0.020) Batch 0.490 (0.468) Loss 1.9407 (1.9301) Accuracy 0.9404.
[05/23 14:54:26 main-logger]: Test: [660/753] Data 0.000 (0.020) Batch 0.495 (0.468) Loss 1.9412 (1.9301) Accuracy 0.9432.
[05/23 14:54:30 main-logger]: Test: [670/753] Data 0.000 (0.019) Batch 0.471 (0.469) Loss 1.9148 (1.9304) Accuracy 0.9655.
[05/23 14:54:35 main-logger]: Test: [680/753] Data 0.000 (0.019) Batch 0.445 (0.469) Loss 2.0036 (1.9307) Accuracy 0.8802.
[05/23 14:54:40 main-logger]: Test: [690/753] Data 0.000 (0.019) Batch 0.450 (0.468) Loss 2.0359 (1.9322) Accuracy 0.8493.
[05/23 14:54:44 main-logger]: Test: [700/753] Data 0.000 (0.019) Batch 0.475 (0.468) Loss 2.0897 (1.9332) Accuracy 0.7885.
[05/23 14:54:49 main-logger]: Test: [710/753] Data 0.000 (0.018) Batch 0.495 (0.469) Loss 1.9306 (1.9344) Accuracy 0.9553.
[05/23 14:54:54 main-logger]: Test: [720/753] Data 0.000 (0.018) Batch 0.518 (0.469) Loss 2.0450 (1.9348) Accuracy 0.8399.
[05/23 14:54:59 main-logger]: Test: [730/753] Data 0.000 (0.018) Batch 0.509 (0.469) Loss 2.0325 (1.9357) Accuracy 0.8489.
[05/23 14:55:04 main-logger]: Test: [740/753] Data 0.000 (0.018) Batch 0.505 (0.470) Loss 1.9576 (1.9373) Accuracy 0.9267.
[05/23 14:55:09 main-logger]: Test: [750/753] Data 0.000 (0.017) Batch 0.429 (0.470) Loss 1.9382 (1.9388) Accuracy 0.9636.
[05/23 14:55:11 main-logger]: Val result: mIoU/mAcc/allAcc 0.7924/0.8580/0.9457.
[05/23 14:55:11 main-logger]: Class_0 Result: iou/accuracy 0.7849/0.8743.
[05/23 14:55:11 main-logger]: Class_1 Result: iou/accuracy 0.4571/0.5205.
[05/23 14:55:11 main-logger]: Class_2 Result: iou/accuracy 0.9509/0.9637.
[05/23 14:55:11 main-logger]: Class_3 Result: iou/accuracy 0.9303/0.9569.
[05/23 14:55:11 main-logger]: Class_4 Result: iou/accuracy 0.5453/0.6761.
[05/23 14:55:11 main-logger]: Class_5 Result: iou/accuracy 0.8850/0.9095.
[05/23 14:55:11 main-logger]: Class_6 Result: iou/accuracy 0.8209/0.8728.
[05/23 14:55:11 main-logger]: Class_7 Result: iou/accuracy 0.6743/0.7425.
[05/23 14:55:11 main-logger]: Class_8 Result: iou/accuracy 0.7418/0.8475.
[05/23 14:55:11 main-logger]: Class_9 Result: iou/accuracy 0.8501/0.9201.
[05/23 14:55:11 main-logger]: Class_10 Result: iou/accuracy 0.9711/0.9858.
[05/23 14:55:11 main-logger]: Class_11 Result: iou/accuracy 0.7396/0.8304.
[05/23 14:55:11 main-logger]: Class_12 Result: iou/accuracy 0.7617/0.8638.
[05/23 14:55:11 main-logger]: Class_13 Result: iou/accuracy 0.7570/0.8575.
[05/23 14:55:11 main-logger]: Class_14 Result: iou/accuracy 0.9135/0.9598.
[05/23 14:55:11 main-logger]: Class_15 Result: iou/accuracy 0.8957/0.9462.
[05/23 14:55:11 main-logger]: <<<<<<<<<<<<<<<<< End Evaluation <<<<<<<<<<<<<<<<<
None
None
None
None
Traceback (most recent call last):
  File "train.py", line 902, in <module>
    main()
  File "train.py", line 90, in main
    mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args.ngpus_per_node, args))
  File "/media/data2/xzz/software/anaconda3/envs/SphereFormer/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/media/data2/xzz/software/anaconda3/envs/SphereFormer/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/media/data2/xzz/software/anaconda3/envs/SphereFormer/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 144, in join
    exit_code=exitcode
torch.multiprocessing.spawn.ProcessExitedException: process 3 terminated with exit code 1
```

**Comment by X-Lai** [comment]
这是正常的，因为在[这一行](https://github.com/dvlab-research/SphereFormer/blob/master/train.py#LL401C15-L401C15)，我们在正常validate结束之后直接用的exit(), 所以就会报上面的错。直接忽略就好了。
