### ISSUE TITLE
CUDA error: an illegal memory access was encountered during training

### ISSUE THREAD

**Issue by markweberdev** [dvlab-research/SphereFormer#31]
Hi,

I can reproduce the following error in two environments. I followed the install guide for the dependencies in one environment, but also tried to use cu111 dependencies for all packages. Both cases, lead to an ` CUDA error: an illegal memory access was encountered` during training.

- Evaluation of provided checkpoints runs fine.
- The error occurs when training with the provided config on nuscenes.
- Using 2 RTX 8000 (48GB vram)

The full error is:
```
[06/02 14:10:24 main-logger]: Epoch: [1/50][10/1758] Data 0.001 (0.864) Batch 1.513 (3.495) Remain 85:18:56 Loss 1.7657 Lr: [0.00599939, 0.00059994] Accuracy 0.4674.
[06/02 14:10:39 main-logger]: Epoch: [1/50][20/1758] Data 0.001 (0.433) Batch 1.465 (2.481) Remain 60:33:22 Loss 1.3113 Lr: [0.00599877, 0.00059988] Accuracy 0.5326.
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:733 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fcf322542f2 in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7fcf3225167b in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x809 (0x7fcf326151f9 in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x54 (0x7fcf3223c3a4 in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x6ea39a (0x7fcfa6cea39a in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x6ea441 (0x7fcfa6cea441 in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python() [0x4cb472]
frame #7: /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python() [0x4b0858]
frame #8: /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python() [0x4c5b50]
frame #9: /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python() [0x4c5b66]
frame #10: /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python() [0x4c5b66]
frame #11: /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python() [0x4c576c]
frame #12: /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python() [0x4a251c]
frame #13: /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python() [0x553803]
frame #14: _PyEval_EvalFrameDefault + 0x2856 (0x4a9536 in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python)
frame #15: _PyFunction_FastCallKeywords + 0x106 (0x4b9d16 in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python)
frame #16: /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python() [0x4ae8df]
frame #17: _PyEval_EvalFrameDefault + 0xa9e (0x4a777e in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python)
frame #18: _PyFunction_FastCallKeywords + 0x106 (0x4b9d16 in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python)
frame #19: /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python() [0x4ae8df]
frame #20: _PyEval_EvalFrameDefault + 0x971 (0x4a7651 in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python)
frame #21: _PyEval_EvalCodeWithName + 0x201 (0x4a5a81 in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python)
frame #22: _PyFunction_FastCallKeywords + 0x29c (0x4b9eac in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python)
frame #23: /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python() [0x4ae8df]
frame #24: _PyEval_EvalFrameDefault + 0x15d6 (0x4a82b6 in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python)
frame #25: _PyEval_EvalCodeWithName + 0x201 (0x4a5a81 in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python)
frame #26: PyEval_EvalCodeEx + 0x39 (0x4a5879 in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python)
frame #27: PyEval_EvalCode + 0x1b (0x54a8db in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python)
frame #28: /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python() [0x564e03]
frame #29: PyRun_StringFlags + 0x7b (0x561a8b in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python)
frame #30: PyRun_SimpleStringFlags + 0x3b (0x5618fb in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python)
frame #31: /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python() [0x53fc27]
frame #32: _Py_UnixMain + 0x3c (0x53fb3c in /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python)
frame #33: <unknown function> + 0x29d90 (0x7fcfba17ed90 in /lib/x86_64-linux-gnu/libc.so.6)
frame #34: __libc_start_main + 0x80 (0x7fcfba17ee40 in /lib/x86_64-linux-gnu/libc.so.6)
frame #35: /usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/bin/python() [0x53f9ee]

Traceback (most recent call last):
  File "train.py", line 902, in <module>
    main()
  File "train.py", line 90, in main
    mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args.ngpus_per_node, args))
  File "/usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/storage/user/webermar/external/SphereFormer/train.py", line 410, in main_worker
    loss_train, mIoU_train, mAcc_train, allAcc_train = train(train_loader, model, criterion, optimizer, epoch, scaler, scheduler, gpu)
  File "/storage/user/webermar/external/SphereFormer/train.py", line 498, in train
    output = model(sinput, xyz, batch)
  File "/usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/storage/user/webermar/external/SphereFormer/model/unet_spherical_transformer.py", line 285, in forward
    output = self.unet(output, xyz, batch)
  File "/usr/wiss/webermar/anaconda3/envs/sphere_pip_cuda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/storage/user/webermar/external/SphereFormer/model/unet_spherical_transformer.py", line 195, in forward
    xyz_next, batch_next = get_downsample_info(xyz, batch, indice_pairs)
  File "/storage/user/webermar/external/SphereFormer/model/unet_spherical_transformer.py", line 56, in get_downsample_info
    valid_pair_in, valid_pair_out = pair_in[valid_mask].long(), pair_out[valid_mask].long()
RuntimeError: CUDA error: an illegal memory access was encountered
```

When using a batchsize of 16 or 14, the error comes up almost immediately, as can be seen above. With a batchsize of 12, the error came after training for 29 epochs. According to `nvidia-smi`, the memory usage is quite low and super far from the maximum.

Did you ever encounter this problem or have any advice on what could cause this issue?

Thanks,
Mark

**Comment by X-Lai** [comment]
According to your issue, it seems the `valid_mask` is out of the range of `pair_in` or `pair_out`. Can you print out the `min` and `max` of `valid_mask`, and also the `pair_in.shape` and `pair_out.shape`?

**Comment by markweberdev** [comment]
Thanks for getting back to me @X-Lai !

I tried to do some manual debugging, but since the error happens not always at the same iteration, this didn't work out.

Instead I put in several assert statements.

```
def get_downsample_info(xyz, batch, indice_pairs):
    torch._assert(xyz.shape[0] == batch.shape[0], "xyz batch shape mismatch")
    pair_in, pair_out = indice_pairs[0], indice_pairs[1]
    torch._assert(pair_in.shape == pair_out.shape, "Pair shape mismatch")

    # print(indice_pairs.shape)
    # print(indice_pairs.min())
    # print(pair_in.min())
    torch._assert(pair_in.min() >= -1, "pair_in minimum is below -1")
    torch._assert((pair_in != -1).sum() >= 1, "pair_in has no valid entries")
    valid_mask = (pair_in != -1)

    torch._assert(pair_in.shape == valid_mask.shape, "Pair and mask shape mismatch")
    valid_pair_in, valid_pair_out = pair_in[valid_mask].long(), pair_out[valid_mask].long()
    torch._assert(valid_pair_in.min() >= 0, "valid Pair in min wrong")
    torch._assert(valid_pair_out.min() >= 0, "valid Pair out min wrong")
    torch._assert(valid_pair_in.max() < xyz.shape[0], "valid Pair in max wrong")
    torch._assert(valid_pair_in.shape == valid_pair_out.shape, "valid Pair shape mismatch")

    xyz_next = scatter_mean(xyz[valid_pair_in], index=valid_pair_out, dim=0)
    batch_next = scatter_mean(batch.float()[valid_pair_in], index=valid_pair_out, dim=0)
    return xyz_next, batch_next
```

The error (same as before) then happens, when the code tries to access `pair_in.min() `. The same thing also happens if I call `indice_pairs.min()`. On the other side, calls to the shape attribute, are fine (neither print not asserts on shape lead to the error). 

At the moment, I cannot make any sense of this, but I also don't know a lot about how spconv datastructures work or how these indices are exactly/internally obtained.

Can you make sense of this?

Thanks!

**Comment by X-Lai** [comment]
The same error happens when executing `pair_in.min()`. So it seems that the true error is prior to this line, because sometimes out-of-range error inside a CUDA kernel will not throw an error immediately and will wait until executing next CUDA kernel (in your case, this is `pair_in.min()`). So to locate the true error, you'd better check the previous several operations by asserting the input range is not out of its range before these operations.

BTW, you can also use `torch.cuda.synchronize()` in between some suspective operations to ensure the lines prior to `torch.cuda.synchronize()` are validated. Because if some operations before `torch.cuda.synchronize()` encounter out-of-range error, then it will throw an error immediately with `torch.cuda.synchronize()`.

**Comment by markweberdev** [comment]
Hi @X-Lai,

Thanks for the tips! I was able to locate the error in UBlock the self.conv, particularly spconv.SparseConv3d. The error is happening in the convolution operation of spconv when the indices are computed. You can find the line here:

https://github.com/traveller59/spconv/blob/47875b2b008e6de87da011c62bb8523d19bc597d/spconv/pytorch/conv.py#L287

Unfortunately, the computed indices have a lot of negative values, which I assume to come from int32 overflows. Since I don't know how these indices are computed, I assume, some flattened hash representation of the 4D indices are used internally. And this overflows with increasing batchsize per GPU. Which is way reducing the batchsize seems to delay the error or makes it disappear (you seem to be able to run everything with a batchsize of 4 per GPU). 

More unfortunately, spconv does not support 64bit indices for these operations yet, so there's no easy fix, instead one has to use more GPUs or has to wait longer for results. (or lowering the spatial voxel dimensions...)

Best,
Mark

**Comment by X-Lai** [comment]
I see. I think your analysis is correct. When you set a large batch size, the product of `bs*H*W*Z` will also become large, even more than INT32_MAX, which causes the error.

**Comment by zhaoxiaolong2020** [comment]
how to fix this bug ？
