### ISSUE TITLE
Problems in training

### ISSUE THREAD

**Issue by TengfeiZeng** [dvlab-research/SphereFormer#42]
Hello author, I have completed the configuration of the environment, and there will be such an error when I start training, I want to know what is the reason. My graphics card only supports 10.x cuda, so I installed the cuda10.2 version.

[08/08 20:57:43 main-logger]: scheduler: Poly. scheduler_update: step
[08/08 20:57:43 main-logger]: lr: [0.006, 0.0006000000000000001]
Traceback (most recent call last):
  File "train.py", line 903, in <module>
    main()
  File "train.py", line 91, in main
    mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args.ngpus_per_node, args))
  File "/home/haoran/miniconda3/envs/spheretransformer/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/haoran/miniconda3/envs/spheretransformer/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/haoran/miniconda3/envs/spheretransformer/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/haoran/miniconda3/envs/spheretransformer/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/media/haoran/DATA2/ztf/SphereFormer-master/train.py", line 411, in main_worker
    loss_train, mIoU_train, mAcc_train, allAcc_train = train(train_loader, model, criterion, optimizer, epoch, scaler, scheduler, gpu)
  File "/media/haoran/DATA2/ztf/SphereFormer-master/train.py", line 580, in train
    allAcc = sum(intersection_meter.sum) / (sum(target_meter.sum) + 1e-10)
TypeError: 'int' object is not iterable

**Comment by bigliuyq** [comment]
你好，我在用多gpu训练时，也遇到了同样的报错，请问你是怎么解决的，谢谢。@TengfeiZeng
