### ISSUE TITLE
The error of waymo dataset to semantic kitti/

### ISSUE THREAD

**Issue by rockywind** [dvlab-research/SphereFormer#49]
Hi, thank you for sharing the great work!
I met the error below when I run the `convert.py`.
I found the error is in the 86th data.
````
[17] ----i ---- 85
[18] split:  training
[19] 85 :  segment-1773696223367475365_1060_000_1080_000_with_camera_labels.tfrecord
[20] ----i ---- 86
[21] split:  training
[22] 86 :  segment-16153607877566142572_2262_000_2282_000_with_camera_labels.tfrecord
[23] Traceback (most recent call last):
[24]   File "/SHFP12/xiaoquan.wang/01_bev/SphereFormer/data/waymo_to_semanticKITTI/convert_my.py", line 14, in <module>
[25]     coverter.convert_all_mp()
[26]   File "/defaultShare/SHFP12/xiaoquan.wang/01_bev/SphereFormer/data/waymo_to_semanticKITTI/lib/waymo2semantickitti.py", line 170, in convert_all_mp
[27]     self.process(i)
[28]   File "/defaultShare/SHFP12/xiaoquan.wang/01_bev/SphereFormer/data/waymo_to_semanticKITTI/lib/waymo2semantickitti.py", line 136, in process
[29]     for data in data_group:
[30]   File "/opt/conda/envs/sphereFormer/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 787, in __next__
[31]     return self._next_internal()
[32]   File "/opt/conda/envs/sphereFormer/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 770, in _next_internal
[33]     ret = gen_dataset_ops.iterator_get_next(
[34]   File "/opt/conda/envs/sphereFormer/lib/python3.8/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3017, in iterator_get_next
[35]     _ops.raise_from_not_ok_status(e, name)
[36]   File "/opt/conda/envs/sphereFormer/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7215, in raise_from_not_ok_status
[37]     raise core._status_to_exception(e) from None  # pylint: disable=protected-access
[38] tensorflow.python.framework.errors_impl.DataLossError: {{function_node __wrapped__IteratorGetNext_output_types_1_device_/job:localhost/replica:0/task:0/device:CPU:0}} truncated record at 561276766' failed with Read less bytes than requested [Op:IteratorGetNext]
````

**Comment by X-Lai** [comment]
It works well in my side. Can you check whether the raw data is downloaded successfully?

**Comment by rockywind** [comment]
Hi, thank you for help!
The below is my converted waymo dataset number.
Is it correct?
![image](https://github.com/dvlab-research/SphereFormer/assets/14838781/54e45252-7a3f-4688-b2f5-c15b63b7ac39)
