### ISSUE TITLE
AssertionError: Table lidarseg not found

### ISSUE THREAD

**Issue by shingszelam** [dvlab-research/SphereFormer#65]
Hello, I want to use the nuscenes-dataset to train a 3D target detection project, but when I convert the data, I get the following error:
v1.0-trainval: train scene(700), val scene(150)
create_info:   0%|          | 1/34149 [00:03<30:20:17,  3.20s/it]Traceback (most recent call last):
  File "/snap/pycharm-professional/356/plugins/python/helpers/pydev/pydevd.py", line 1500, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/356/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/dl/csl/SphereFormer/detection/pcdet/datasets/nuscenes/nuscenes_dataset.py", line 322, in <module>
    max_sweeps=dataset_cfg.MAX_SWEEPS,
  File "/home/dl/csl/SphereFormer/detection/pcdet/datasets/nuscenes/nuscenes_dataset.py", line 286, in create_nuscenes_info
    test='test' in version, max_sweeps=max_sweeps
  File "/home/dl/csl/SphereFormer/detection/pcdet/datasets/nuscenes/nuscenes_utils.py", line 285, in fill_trainval_infos
    lidarseg_labels_filename = nusc.get('lidarseg', ref_sd_token)['filename']
  File "/home/dl/anaconda3/envs/spt/lib/python3.7/site-packages/nuscenes/nuscenes.py", line 214, in get
    assert table_name in self.table_names, "Table {} not found".format(table_name)
AssertionError: Table lidarseg not found

But I downloaded lidarseg, and the data set structure is arranged as follows:
-lidarseg
--lidarseg
---v1.0-mini
---v1.0-trainval
---v1.0-test
--v1.0-mini
--v1.0-trainval
--v1.0-test
The following folder stores two json files.

**Comment by calvindongzw** [comment]
Hi, i got the same issue? Have you solved?

**Comment by calvindongzw** [comment]
> Hi, i got the same issue? Have you solved?

Oh, never mind. Wrong nuscenes-devkit version, don't use 1.0.5 but the updated one.

**Comment by minhoooo1** [comment]
> > Hi, i got the same issue? Have you solved?
> 
> Oh, never mind. Wrong nuscenes-devkit version, don't use 1.0.5 but the updated one.

could you please tell me which version of nuscenes-devkit is useful?
